apiVersion: v1
kind: Pod
metadata:
  name: marketplace-app
  labels:
    component: marketplace
spec:
  containers:
    - name: marketplace
      image: m1gormley/marketplace
      ports:
        - containerPort: 3000