apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace
spec:
  replicas: 1
  selectcor:
    matchLabels:
      component: marketplace
    template:
      metadata:
        labels:
          component: marketplace
      spec:
        containers:
          - name: marketplace
            image: m1gormley/marketplace
            ports:
              - containerPort: 3000