#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

Yellow='\033[0;33m'
NC='\033[0m'
local_branch="$(git rev-parse --abbrev-ref HEAD)"
valid_branch_regex="^(feat|bugfix|docs|chore)\/.*$"
message="\nBranch names in this project must adhere to this contract:${Yellow} $valid_branch_regex.${NC}\n Your commit will be rejected. You should rename your branch to a valid name and try again.\n"

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo "$message"
    exit 1
fi

npx lint-staged
npm run type-check